# meta_product_name: "aicery"
# meta_title: "aicery - your ai driven grocery list"
# meta_description: "aicery helps you save time and money as you shop for groceries"
# meta_image: "metaImage.png"

meta_product_name: "Product Name"
meta_title: "Product name - Product tagline"
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
